### ISSUE TITLE
【コードを授ける・code include】コードの転載権限を授けて

### ISSUE THREAD

**Issue by kirigakuretora** [degarashi0913/FAManagementStudio#12]
はじめまして、霧隠虎（きりがくれとら）です。PJのモデルか 転載権限を授けて頂けませんか。

よろしくお願い致します。

**Comment by bonjin6770** [comment]
hi,kirigakuretora.i'm bonjin.
thank you for your issue.
you from taiwan?
sorry, i couldn't understand your issue details in japanese.
please tell me about your issue in english.

>> PJのモデル
what's it? PJ's Model?

**Comment by kirigakuretora** [comment]
Dear bonjin6770:

Yes, Kirigakuretora from Taiwan.
I Repeat My question:

> Can I citation「**FAManagementStudio / Model**」 code to my project?

PJのモデル = folder "Model" in FAManagementStudio Project 


Sincerely,
Kirigakuretora

**Comment by bonjin6770** [comment]
hi, kirigakuretora.

thanks for your issue in English.
i understood it.
ofcouse, it's ok.
i'll be glad if you use our project's code!
I hope this will be of some help.

thx!

**Comment by kirigakuretora** [comment]
bonjin6770先輩､ありがとう。
