### ISSUE TITLE
【要望機能】SELECT結果の行数表示

### ISSUE THREAD

**Issue by gktnkmr** [degarashi0913/FAManagementStudio#2]
SELECTした行数を、画面下部に表示してほしい。

**Comment by kowill** [comment]
複数結果セットがある場合、どうやって表示するか案あります？

**Comment by gktnkmr** [comment]
すごい雑な感じですが、結果セットのテンプレートにテキストブロック突っ込めばいいかなあ、と。

`                    <ListBox.ItemTemplate>
                        <DataTemplate>
                            <Grid>
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="*"/>
                                    <RowDefinition Height="20"/>
                                </Grid.RowDefinitions>
                                <toolkit:DataGrid Name="ResultView" HorizontalAlignment="Stretch"
                                          ItemsSource="{Binding}" Margin="0,0,0,5" EnableColumnVirtualization="True" EnableRowVirtualization="True"
                                          VirtualizingStackPanel.IsVirtualizing="True" VirtualizingStackPanel.VirtualizationMode="Recycling" 
                                          CanUserAddRows="False" CanUserDeleteRows="False"
                                          MaxWidth="{Binding Path=ActualWidth, ElementName=ResultGrid, Converter={StaticResource WidthConverter}}"
                                          Width="{Binding MaxWidth, RelativeSource={RelativeSource Self}}"
                                          MaxHeight="{Binding Path=ActualHeight, ElementName=ResultRow, Converter={StaticResource HeightConverter}}"
                                          IsReadOnly="True" Grid.Row="0">
                                </toolkit:DataGrid>
                                <TextBlock Text="秒とか行   " Grid.Row="1" HorizontalAlignment="Right" VerticalAlignment="Center"/>
                            </Grid>
                        </DataTemplate>
                    </ListBox.ItemTemplate>
`

バインドする内容によって詳細は変わりますが。
